package io.itch.mgdsstudio.battlecity.game.dataloading;

public enum Keys {
    MONEY, LIFES, EXP, LEVEL, TYPE, LAST_COMPLETED_LEVEL, LAST_REPEATED_LEVEL, KILLED_ON_LEVEL_1, KILLED_ON_LEVEL_2, ROTATING_MAX_VELOCITY, ROTATING_ACCELERATE, FORWARD_MAX_VELOCITY_IN_WORLD_UNITS, BACKWARD_MAX_VELOCITY_IN_WORLD_UNITS, TURRET_ROTATING_MAX_VELOCITY, TURRET_ROTATING_ACCELERATE, NORMAL_BULLET_VELOCITY, FAST_BULLET_VELOCITY,
    TIME_BETWEEN_SHOTS_FOR_SIMPLE_CANNON, TIME_BETWEEN_SHOTS_FOR_UPGRADED_CANNON, CHASSIS_UPGRADE, TOWER_UPGRADE, MOTOR_UPGRADE, HP, MAX_ROCKETS, AMMO_FOR_ACTUAL_WEAPON, MINES, TIME_TO_BLOCK_ENEMIES,
    FORWARD_MAX_VELOCITY_IN_WORLD_UNITS_AFTER_MOTOR_UPGRADE, BACKWARD_MAX_VELOCITY_IN_WORLD_UNITS_AFTER_MOTOR_UPGRADE, MAX_TIME_FOR_ENGINE_PERFORMANCE;
}
