package io.itch.mgdsstudio.battlecity.menu;

public enum MenuType {
    MAIN,OPTIONS, CAMPAIGN,CONTINUE_LAST_GAME, HOW_TO_PLAY_FROM_OPTIONS, HOW_TO_PLAY_FROM_CAMPAIGN,CREDITS,CHOOSE_LEVEL,WEAPON_HANDLER, USER_LEVELS, MAIN_LEVEL_LOADING, SINGLE_MISSION_LOADING, EDITOR_LOADING, EXIT_MENU, INTRO_MENU, SHOP, END_CUTSCENE_MENU,
    DO_YOU_WANT_TO_CHANGE_COLOR, BERET_COLOR_CHANGING, WOULD_YOU_LIKE_TO_LEARN_HOW_TO_PLAY_MENU, DO_YOU_LIKE_OUR_GAME_MENU, HELP_VARIANTS_MENU, REWARDED_ADDS_MENU, LEVEL_RESULTS_MENU, YOU_NEED_TO_RELAUNCH_GAME,NO_SIGNAL, FULL_SCREEN_ADD_MENU,

    SINGLE_MISSION_COMPLETED, SINGLE_MISSION_LOOSED,
    SELECT_GAME_MODE, SELECT_MULTIPLAYER_MODE, CAMPAIGN_RETURN_IN_GARAGE, SINGLE_MISSIONS, EDITOR_PRELOADING_WINDOW;

}
